version: 2

sources:
  - name: your_source_name  # Replace with the name of your source
    database: your_database # Replace with your database name (e.g., BigQuery project ID)
    schema: your_schema     # Replace with your schema name (e.g., dataset name in BigQuery)
    tables:
      - name: weather_data  # The name of the source table
        columns:
          - name: place
            tests:
              - not_null
              - unique
          - name: value
            tests:
              - not_null
          - name: unit
            tests:
              - not_null
              - accepted_values:
                  values: ['C', 'F']  # Example: Ensure unit is either 'C' or 'F'
          - name: recordTime
            tests:
              - not_null
