version: 2

sources:
  - name: zoomcamp-project-454404 # Replace with the name of your source
    database: zoomcamp
    schema: weather_data    # Replace with your schema name (e.g., dataset name in BigQuery)
    tables:
      - name: weather_data  # The name of the source table
        columns:
          - name: place
            tests:
              - not_null
              - unique
          - name: value
            tests:
              - not_null
          - name: unit
            tests:
              - not_null
              - accepted_values:
                  values: ['C', 'F']  # Example: Ensure unit is either 'C' or 'F'
          - name: recordTime
            tests:
              - not_null
